CREATE TABLE flights (
DAY_OF_WEEK int not null,
AIRLINE varchar(2) not null,
FLIGHT_NUMBER varchar(4) not null,
TAIL_NUMBER varchar(6),
ORIGIN_AIRPORT varchar(3) not null,
DESTINATION_AIRPORT varchar(3) not null,
SCHEDULED_DEPARTURE timestamp not null,
DEPARTURE_TIME timestamp,
DEPARTURE_DELAY int,
TAXI_OUT int,
WHEELS_OFF timestamp,
SCHEDULED_TIME integer not null,
ELAPSED_TIME int,
AIR_TIME int,
DISTANCE int not null,
WHEELS_ON timestamp,
TAXI_IN int,
SCHEDULED_ARRIVAL timestamp not null,
ARRIVAL_TIME timestamp,
ARRIVAL_DELAY int,
DIVERTED int not null default 0,
CANCELLED int not null default 0,
CANCELLATION_REASON varchar(2),
AIR_SYSTEM_DELAY int,
SECURITY_DELAY int,
AIRLINE_DELAY int,
LATE_AIRCRAFT_DELAY int,
WEATHER_DELAY int
);

CREATE TABLE flights2 ( 
YEAR int not null,
MONTH int not null,
DAY int not null,
DAY_OF_WEEK int not null,
AIRLINE varchar(2) not null,
FLIGHT_NUMBER varchar(4) not null,
TAIL_NUMBER varchar(6),
ORIGIN_AIRPORT varchar(3) not null,
DESTINATION_AIRPORT varchar(3) not null,
SCHEDULED_DEPARTURE int not null,
DEPARTURE_TIME int,
DEPARTURE_DELAY int,
TAXI_OUT int,
WHEELS_OFF int,
SCHEDULED_TIME int not null,
ELAPSED_TIME int,
AIR_TIME int,
DISTANCE int not null,
WHEELS_ON int,
TAXI_IN int,
SCHEDULED_ARRIVAL int not null,
ARRIVAL_TIME int,
ARRIVAL_DELAY int,
DIVERTED int not null default 0,
CANCELLED int not null default 0,
CANCELLATION_REASON varchar(2),
AIR_SYSTEM_DELAY int,
SECURITY_DELAY int,
AIRLINE_DELAY int,
LATE_AIRCRAFT_DELAY int,
WEATHER_DELAY int
);