CREATE TABLE flights (
DAY_OF_WEEK int not null,
AIRLINE varchar(2) not null,
FLIGHT_NUMBER varchar(4) not null,
TAIL_NUMBER varchar(5),
ORIGIN_AIRPORT varchar(3) not null,
DESTINATION_AIRPORT varchar(3) not null,
SCHEDULED_DEPARTURE timestamp not null,
DEPARTURE_TIME timestamp,
DEPARTURE_DELAY int not null,
TAXI_OUT int,
WHEELS_OFF timestamp,
SCHEDULED_TIME timestamp not null,
ELAPSED_TIME int,
AIR_TIME int,
DISTANCE int not null,
WHEELS_ON timestamp,
TAXI_IN int,
SCHEDULED_ARRIVAL timestamp not null,
ARRIVAL_TIME timestamp,
ARRIVAL_DELAY int,
DIVERTED int not null default 0,
CANCELLED int not null default 0,
CANCELLATION_REASON varchar(2),
AIR_SYSTEM_DELAY int,
SECURITY_DELAY int,
AIRLINE_DELAY int,
LATE_AIRCRAFT_DELAY int,
WEATHER_DELAY int
);
